#! /bin/bash -e


if [[ -z "$PROJECT" ]]; then
  export PROJECT="nvros-base"
fi

if [[ -z "$PROJECT_DIR" ]]; then
	export PROJECT_DIR="${BASEDIR}/build/${PROJECT}"
fi


pushd "${PROJECT_DIR}"

rm completed latest* || echo project not fully completed, cleaning anyway.
btrfs subv del chroot || rm -rf chroot
btrfs subv cre chroot

if [[ "$1" == "packages" ]]; then
  btrfs subv del packages
  btrfs subv cre packages
fi

popd
