#!/bin/bash
mkdir -p ${CHROOT_DIR}/etc/portage/sets/
for((i=0;i<$(${PARSERS}/config/getconfig sets "#");i++)); do
    cp ${CONFIG_DIR}/sets/$(${PARSERS}/config/getconfig sets $i) ${CHROOT_DIR}/etc/portage/sets/
done
