#!/bin/bash -evx
pushd ${PROJECT_DIR}
rm -rf image/var/db/repos/*
rm -rf image/var/cache/distfiles/*
rm -rf image/var/cache/binpkgs/*
rm -rf image/usr/portage/distfiles/*
rm -rf image/usr/portage/packages/*

sed -i -E 's_distcc__' image/etc/portage/make.conf || echo "No distcc entries to remove"

if [[ -f image/etc/distcc/hosts ]]
then
	echo "127.0.0.1" > image/etc/distcc/hosts
fi

rm -f image/wget-log*
exit 0
