#!/usr/bin/python3.9
import json
import os
import sys
import shutil


def system(*args):
    os.system(*args) and sys.exit(1)


CONFIG_DIR = os.environ['CONFIG_DIR']
PROJECT_DIR = os.environ['PROJECT_DIR']
PROJECT = os.environ['PROJECT']
CHROOT_DIR = os.environ['CHROOT_DIR']
PARSERS = os.environ['PARSERS']
SCRIPTS = os.environ['SCRIPTS']


os.chdir(CHROOT_DIR)
os.chdir("etc/portage")
with open("make.conf") as f:
    lines = f.readlines()


with open("make.conf", "w") as f:
    for line in lines:
        if line.startswith("FEATURES"):
            line = line[:-2] + " " + str.join(" ", sys.argv[1:]) + line[-2:]
        f.write(line)
