#!/bin/bash -e
source "${SCRIPTS}/functions.sh"

echo "Running $@"

function finish
{
        rm -f ${PROJECT_DIR}/chroot/em-$$
}
trap finish EXIT

echo "source /etc/profile" > "${PROJECT_DIR}/chroot/em-$$"
service_count=$($PARSERS/config/getconfig services "#")
service_manager=$($PARSERS/config/getconfig service-manager)
for((i=0;$i<$service_count;i++)); do
    key=$($PARSERS/config/getconfig services $i)
    value=$($PARSERS/config/getconfig services $key)
    ${service_manager} ${key} ${value}  >>  "${PROJECT_DIR}/chroot/em-$$"
done

"${SCRIPTS}/chroot.py" /usr/bin/env -i bash --login /em-$$

rm "${PROJECT_DIR}/chroot/em-$$"
