#!/usr/bin/python3.9
import json
import os
import sys

sys.path.insert(0, os.environ['CONFIG_DIR'])

target = os.environ['CHROOT_DIR']+'/em-config'

from pyconfig import config

with open(f'{target}.json', 'w') as f:
    json.dump(config, f)

emconfig = os.path.dirname(__file__)+'/emconfig'


os.system(f'cp {emconfig} {target}')
