#!/usr/bin/env python3
import json

import sys
import os

if 'em-config.json' not in os.listdir('/'):
    prefix = os.environ['CHROOT_DIR']
else:
    prefix = ''

with open(f'{prefix}/em-config.json', 'r') as f:
    config = json.load(f)

t = config

for i in sys.argv[1:]:
    if i[0] == '*':
        print(str.join(i[1:], t))
        break
    if i.isdigit():
        i = int(i)
        if isinstance(t, dict):
            t = list(t)[i]
            print(t)
            break
    if i == '#':
        print(len(t))
        break
    t = t[i]
else:
    print(t)
