#!/usr/bin/python3.9
import sys
import os
sys.path.insert(0, os.environ['CONFIG_DIR'])

from pyconfig import config

t = config

for i in sys.argv[1:]:
    if i[0] == '*':
        print(str.join(i[1:], t))
        break
    if i.endswith('?'):
        print(t.get(i[:-1], ""))
        break
    if i.isdigit():
        i = int(i)
        if isinstance(t, dict):
            t = list(t)[i]
            print(t)
            break
    if i == '#':
        print(len(t))
        break

    t = t[i]
else:
    print(t)
