#!/usr/bin/python
import sys
import os
sys.path.insert(0, os.environ['CONFIG_DIR'])

import config
config = getattr(config, os.environ['PROJECT'])

t = config
    
for i in sys.argv[1:]:
    if i[0] == '*':
        print(str.join(i[1:], t))
        break
    if i.isdigit():
        i = int(i)
    if i == '#':
        print(len(t))
        break
    t = t[i]
else:
    print(t)
