#!/usr/bin/env python3

import os
import sys
import shutil

def system(*args):
    os.system(*args) and sys.exit(1)

CONFIG_DIR = os.environ['CONFIG_DIR']
PROJECT_DIR = os.environ['PROJECT_DIR']
PROJECT = os.environ['PROJECT']
CHROOT_DIR = os.environ['CHROOT_DIR']
PARSERS = os.environ['PARSERS']
SCRIPTS = os.environ['SCRIPTS']
BINPKGS_DIR = os.environ['BINPKGS_DIR']
DISTFILES_DIR = os.environ['DISTFILES_DIR']

print(f"Copying etc config files for {PROJECT}")

sys.path.insert(0, CONFIG_DIR)
from pyconfig import config

def copyconf(conf, file):
    if isinstance(conf, dict):
        with open(file, 'w') as f:

            for key, val in conf.items():
                if isinstance(val, (list, tuple, set)):
                    val = str.join(" ", val)
                    val = json.dumps(val)
                print(f"{key}={val}", file=f)
    else:
        if not conf.startswith("/"):
            conf = f'{CONFIG_DIR}/{conf}'
        shutil.copy2(conf, file)

def copydir(conf, dest):
    for node, content in conf.items():
        if node.endswith('/'):
            d = os.path.join(dest, node)
            system(f'mkdir -p {repr(d)}')
            copydir(content, d)
        else:
            copyconf(content, os.path.join(dest, node))


copydir(config['etc'], f"{CHROOT_DIR}/etc")

#additional restrictions


system(f"chmod 700 {CHROOT_DIR}/etc/shadow")
system(f"chmod 755 {CHROOT_DIR}/etc/profile")

system(f"{SCRIPTS}/chroot.py /usr/sbin/locale-gen")
system(f"{SCRIPTS}/chroot.py /usr/sbin/env-update")

