#! /bin/bash -e
cp "/usr/bin/qemu-arm" "$PROJECT_DIR/chroot/usr/bin/qemu-x86_64-arm"
cp "/usr/bin/qemu-aarch64" "$PROJECT_DIR/chroot/usr/bin/qemu-x86_64-aarch64"

if [[ ! -e /proc/sys/fs/binfmt_misc/arm ]]; then
  echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-x86_64-arm:' > /proc/sys/fs/binfmt_misc/register

fi

if [[ ! -e /proc/sys/fs/binfmt_misc/aarch64 ]]; then
  echo ':aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\xB7\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-x86_64-aarch64:' > /proc/sys/fs/binfmt_misc/register

fi

