#!/bin/bash

groupcount=$(/em-config groups "#")

usercount=$(/em-config users "#")


for((i=0;i<$groupcount;i++)); do
    groupadd -g $(/em-config groups $i gid) $(/em-config groups $i name)
done

for((i=0;i<$usercount;i++)); do
    useradd \
	-g $(/em-config users $i group) \
	-G $(/em-config users $i groups | python -c 'print(str.join(",",eval(input(""))))') \
	-s $(/em-config users $i shell) \
	-u $(/em-config users $i uid) \
	$(/em-config users $i name)

    echo $(/em-config users $i name):$(/em-config users $i password) | chpasswd -c $(/em-config users $i format)
done
