#!/bin/bash -ex

function finish
{
	ret=$?
	rm -f "${PROJECT_DIR}/chroot/setupusers"
	exit $ret
}
trap finish EXIT

cp "$(dirname $0)/setupusers" "${PROJECT_DIR}/chroot/setupusers"
chmod +x "${PROJECT_DIR}/chroot/setupusers"

"${SCRIPTS}/chroot.py" /setupusers
