#!/bin/bash -evx

function finish
{
    rm -f "${PROJECT_DIR}/chroot/setupusers"
}
trap finish EXIT

cp "$(dirname $0)/setupusers" "${PROJECT_DIR}/chroot/setupusers"
chmod +x "${PROJECT_DIR}/chroot/setupusers"

"${SCRIPTS}/chroot.py" /setupusers
