#!/bin/bash -e
#Install binary packages for things that don't compile when called from a python script, but that are otherwise fine.

#Currently only netpbm.  Not sure why.

#Use as a last resort.
if [[ ! -d "$BINPKGS_DIR" ]]; then
  mkdir "$BINPKGS_DIR"
  cp -r "$BINARY_ASSETS"/binaryWorkarounds/$PROJECT/* "$BINPKGS_DIR" || echo "No binary workarounds detected."
fi

