#!/bin/bash -e
#Install binary packages for things that don't compile when called from a python script, but that are otherwise fine.

#Currently only netpbm.  Not sure why.

#Use as a last resort.
if [[ ! -d "$PROJECT_DIR/packages" ]]; then
  mkdir "$PROJECT_DIR/packages"
  cp -r $BINARY_ASSETS/binaryWorkarounds/$PROJECT/* $PROJECT_DIR/packages || echo "No binary workarounds detected."
fi

