#!/usr/bin/env python3
import os
import sys

os.chdir(os.environ['CHROOT_DIR'])
os.chdir("boot")
with open("config.txt") as f:
    lines = f.readlines()

with open("config.txt", "w") as f:
    for line in lines:
        f.write(line)
        if line.startswith("kernel="):
            f.write(f"initramfs {sys.argv[1]}\n")
