#!/bin/bash -e
source "$BASEDIR/scripts/functions.sh"


echo "Changing root password to GenPi64@."

echo "source /etc/profile" > "${PROJECT_DIR}/image/em-$$"
echo "chpasswd <<< root:GenPi64@" >> "${PROJECT_DIR}/image/em-$$"
CHROOT_DIR="${PROJECT_DIR}/image" "${SCRIPTS}/chroot.py" /usr/bin/env -i bash --login /em-$$

rm -r "${PROJECT_DIR}/chroot/em-$$"
