#!/bin/bash -e
source "$BASEDIR/scripts/functions.sh"

echo "Changing root password to GenPi64@."

function finish
{
        rm -f ${PROJECT_DIR}/chroot/em-$$
}
trap finish EXIT

echo "source /etc/profile" > "${PROJECT_DIR}/chroot/em-$$"
echo "chpasswd <<< root:GenPi64@" >> "${PROJECT_DIR}/chroot/em-$$"
CHROOT_DIR="${PROJECT_DIR}/chroot" "${SCRIPTS}/chroot.py" /usr/bin/env -i bash --login /em-$$

rm -r "${PROJECT_DIR}/chroot/em-$$"
