#!/usr/bin/python3.9
import os
import sys
from sys import exit

os.chdir(os.environ['PROJECT_DIR'])
sys.path.insert(0, os.environ['CONFIG_DIR'])

import config
config = getattr(config, os.environ['PROJECT'])

image = config['image']

with open("image/etc/fstab", "w") as fstab:
    for p in image['mount-order']:
        partuuid = image['partitions'[p]['partuuid']
        target = image['partitions'][p]['mount-point']
        fstype = image['partitions'][p]['format']
        options = image['partitions'][p]['mount-options']
        options = options.replace("zstd:15", "zstd")
        fstab.write(f'PARTUUID="{partuuid}"\t{target}\t{fstype}\t{options}\t0\t0\n')
