#!/usr/bin/env python3
import os
import sys
from sys import exit

os.chdir(os.environ['PROJECT_DIR'])
sys.path.insert(0, os.environ['CONFIG_DIR'])

from pyconfig import config

image = config['image']

with open("image/etc/fstab", "a") as fstab:
    for p in image['mount-order']:
        partuuid = image['partitions'][p]['partuuid']
        target = image['partitions'][p]['mount-point']
        fstype = image['partitions'][p]['filesystem']
        options = image['partitions'][p]['mount-options']
        options = options.replace("zstd:15", "zstd")
        dump = image['partitions'][p]['fstab-dump']
        fsckPass = image['partitions'][p]['fstab-fsck-pass']
        fstab.write(f'PARTUUID="{partuuid}"\t{target}\t{fstype}\t{options}\t{dump}\t{fsckPass}\n')
