#!/usr/bin/python

import os
from sys import exit

os.chdir(os.environ['PROJECT_DIR'])
sys.path.insert(0, os.environ['CONFIG_DIR'])

import config
config = getattr(config, os.environ['PROJECT'])

with open("image/etc/init.d/autoexpand-root") as f:
    aer = f.read()

aer = aer.replace('DEFAULTPW="raspberrypi64"', f'DEFAULTPW="{config["users"][0]["password"]}"')

if config['image']['partitions'][config['image']['partitions']['mount-order'][0]]['type'] == 'btrfs':
    aer = aer.replace('if ! resize2fs -f "${ROOTPART}" &>/dev/null; then',
                      'if ! btrfs filesystem resize max "${ROOTPART}" &>/dev/null; then')
    aer = aer.replace("# do an online resize of the root partition's ext4 filing system",
                      "# do an online resize of the root partition's btrfs filing system")

with open("image/etc/init.d/autoexpand-root", 'w') as f:
    f.write(aer)
