#!/usr/bin/python

import os
from sys import exit
import sys

os.chdir(os.environ['PROJECT_DIR'])
sys.path.insert(0, os.environ['CONFIG_DIR'])

os.system('touch image/boot/autoexpand_root_partition')

import config
config = getattr(config, os.environ['PROJECT'])

with open("image/etc/init.d/autoexpand-root") as f:
    aer = f.read()
    
aer = aer.replace('DEFAULTPW="raspberrypi64"', f'DEFAULTPW="{config["users"][0]["password"]}"')

image = config['image']
p = image['mount-order'][0]
fmt = image['partitions'][p]['format']

if fmt == 'btrfs':
    aer = aer.replace('if ! resize2fs -f "${ROOTPART}" &>/dev/null; then',
                      'if ! btrfs filesystem resize max "/" &>/dev/null; then')
    aer = aer.replace("# do an online resize of the root partition's ext4 filing system",
                      "# do an online resize of the root partition's btrfs filing system")

with open("image/etc/init.d/autoexpand-root", 'w') as f:
    f.write(aer)
