#!/bin/bash -e
source "$BASEDIR/scripts/functions.sh"

echo "Running grub tasks"

function finish
{
        rm -f ${PROJECT_DIR}/chroot/em-$$
}
trap finish EXIT

echo "source /etc/profile" > "${PROJECT_DIR}/image/em-$$"
echo "grub-install $(cat $PROJECT_DIR/loopdevice.txt)" >> "${PROJECT_DIR}/image/em-$$"
echo "grub-mkconfig -o /boot/grub/grub.cfg" >> "${PROJECT_DIR}/image/em-$$"
CHROOT_DIR="${PROJECT_DIR}/image" "${SCRIPTS}/chroot.py" /usr/bin/env -i bash --login /em-$$

rm --force "${PROJECT_DIR}/image/em-$$"
