#!/usr/bin/env python3

import os
import sys
import subprocess

os.chdir(os.environ['CHROOT_DIR'])

p = subprocess.Popen([f'{os.environ["SCRIPTS"]}/crudini', *sys.argv[1:]], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = p.communicate()

if p.returncode != 0:
    sys.stderr.write(stderr.decode())
    sys.stdout.write(stdout.decode())
    sys.exit(p.returncode)
else:
    sys.stderr.write(stdout.decode())
    sys.stdout.write(stdout.decode())
    sys.exit(0)
