#! /bin/bash -e

rm "$PROJECT_DIR"/chroot/em-* || echo "no scripts to clean"

tar --zstd --file $PROJECT_DIR/latest-$PROJECT.tar.zst --create --preserve-permissions --numeric-owner --xattrs --acls --directory "$PROJECT_DIR/chroot" .
