#!/bin/bash -e

rm "$CHROOT_DIR"/em-* || echo "no scripts to clean"

tar --zstd -f $PROJECT_DIR/latest-$PROJECT.tar.zst --create --preserve-permissions --numeric-owner --xattrs --acls --directory "$CHROOT_DIR" .

