#!/bin/bash -ex
source "$BASEDIR/scripts/functions.sh"

echo "Running $@"

function finish
{
        rm -f "${PROJECT_DIR}/chroot/em-$$"
}
trap finish EXIT

cat <<- EOF > "${PROJECT_DIR}/chroot/em-$$"
        #!/usr/bin/env bash
        set -evx
        source /etc/profile
        $@
EOF
chmod +x "${PROJECT_DIR}/chroot/em-$$"

"${SCRIPTS}/chroot.py" /em-$$
