#!/bin/bash -evx
source "$BASEDIR/scripts/functions.sh"

echo "Running $@"

function finish
{
        rm -f "${PROJECT_DIR}/chroot/em-$$"
}
trap finish EXIT

cat <<- EOF > "${PROJECT_DIR}/chroot/em-$$"
        #!/usr/bin/env bash
        set -evx
        source /etc/profile
        $@
EOF

"${SCRIPTS}/chroot.py" /em-$$
