#!/usr/bin/env python3

import os
import sys
from datetime import datetime

os.chdir(os.environ['PROJECT_DIR'])
sys.path.insert(0, os.environ['CONFIG_DIR'])

with open("image/etc/genpi-release", "a") as release:
    print(f"ENV: {os.environ}")
    try:
        if os.environ['CI']:
            TIMESTAMP = os.environ['BUILD_TIMESTAMP']
            NODE_NAME = os.environ['NODE_NAME']

            release.write(f"Built at: {TIMESTAMP}\nBuilt on node: {NODE_NAME}")
    except KeyError as e:
        TIMESTAMP = datetime.now().strftime("%d-%m-%Y")

        release.write(f"Built at: {TIMESTAMP}\nMANUAL BUILD")

