#! /bin/bash -e

source "$BASEDIR/scripts/functions.sh"

pychroot "${PROJECT_DIR}/chroot" /usr/bin/emerge dracut

pychroot "${PROJECT_DIR}/chroot"		\
	/usr/bin/dracut				\
		--force				\
		--modules base			\
		--modules bash			\
		--modules btrfs			\
		--modules udev-rules		\
		--modules fs-lib		\
		--modules shutdown		\
		--filesystems btrfs		\
		--hardlink			\
		--strip				\
		--early-microcode		\
		--xz				\
		--no-kernel			\
		--reproducible			\
		--kver 0			\
		/boot/initramfs.cpio.xz

