#!/bin/bash -ev

if [[ ! -d "${PROJECT_DIR}/chroot" ]]; then
  mkdir "${PROJECT_DIR}/chroot"
fi

pushd "$PROJECT_DIR/chroot" || exit 1

stage3tb=$(${PARSERS}/config/getconfig stage3)

if [ -f "${BINARY_ASSETS}/stage3/${stage3tb}.DIGESTS" ]; then
    if [[ $(head -n 4 "${BINARY_ASSETS}/stage3/${stage3tb}.DIGESTS"  | tail -n 1 | cut -f 1 -d' ') == $(sha512sum "${BINARY_ASSETS}/stage3/${stage3tb}") ]]; then
        echo "Stage3 archive is invalid, did your download fail?"
        exit 1
    fi
fi

tar -xapf "${BINARY_ASSETS}/stage3/${stage3tb}" --xattrs --exclude="dev/*" || tar --recursive-unlink -Uxapf "${BINARY_ASSETS}/stage3/${stage3tb}" --xattrs --exclude="dev/*" || rm "${BINARY_ASSETS}/stage3/${stage3tb}*"

popd
