#!/bin/bash -evx
source "$BASEDIR/scripts/functions.sh"

ckmkdir "${BINPKGS_DIR}"
ckmkdir "${DISTFILES_DIR}"
ckmkdir "${PROJECT_DIR}/chroot/var/cache/binpkgs"
ckmkdir "${PROJECT_DIR}/chroot/var/cache/distfiles"

if [[ ! -z "$2" ]]; then
  USE="export USE='${2}'"
else
  unset USE
fi

echo "emerging with $USE"

function finish
{
	rm -f ${PROJECT_DIR}/chroot/em-$$
}
trap finish EXIT

cat <<- EOF > "${PROJECT_DIR}/chroot/em-$$"
	#!/usr/bin/env bash -evx
	source /etc/profile
	export SHELL="/bin/bash"
	export TERM="linux"
	${USE}
	${EXTRA_EMERGE_ENV}
	emerge $1
EOF

"${SCRIPTS}/chroot.py" --login /em-$$

