#!/bin/bash -ex
source "$BASEDIR/scripts/functions.sh"

ckmkdir "${BINPKGS_DIR}"
ckmkdir "${DISTFILES_DIR}"
ckmkdir "${PROJECT_DIR}/chroot/var/cache/binpkgs"
ckmkdir "${PROJECT_DIR}/chroot/var/cache/distfiles"

if [[ ! -z "$2" ]]; then
  USE="export USE='${2}'"
else
  unset USE
fi

echo "emerging with $USE"

function finish
{
	ret=$?
	rm -f "${PROJECT_DIR}/chroot/em-$$"
	exit $ret
}
trap finish EXIT

cat <<- EOF > "${PROJECT_DIR}/chroot/em-$$"
	#!/usr/bin/env bash
	set -evx
	source /etc/profile
	export SHELL="/bin/bash"
	export TERM="linux"
	export MAKEOPTS="-j$(nproc) -l$(nproc)"
	${USE}
	${EXTRA_EMERGE_ENV}
	unset SCRIPTS
	emerge $1
EOF

chmod +x "${PROJECT_DIR}/chroot/em-$$"

"${SCRIPTS}/chroot.py" "/em-$$"

