#!/usr/bin/env python3
import os
from sys import exit
import sys

os.chdir(os.environ['PROJECT_DIR'])
sys.path.insert(0, os.environ['CONFIG_DIR'])

from pyconfig import config

image = config['image']
with open("image/boot/cmdline.txt", "w") as cmdline:
    p = image['mount-order'][0]
    partition=image['partitions'][p]
    e = dict(PARTUUID=partition['partuuid'], fstype=partition['format'])
    cmdline.write(config['cmdline'] % e)
